/**
 * Scrape knockout match results from the openfootball worldcup.json.
 * Fetches https://raw.githubusercontent.com/openfootball/worldcup.json/master/2026/worldcup.json
 * filters knockout matches (those with a "num" field, IDs 73–104), and writes
 * results to src/data/knockout-phase-scrape-results.ts.
 *
 * Score priority: et > ft.  "p" (penalties) determines the winner when present.
 *
 * Usage: npx tsx scripts/scrape-knockout.ts
 */

import { writeFileSync } from "fs";

const JSON_URL = "https://raw.githubusercontent.com/openfootball/worldcup.json/master/2026/worldcup.json";
const OUT = "src/data/knockout-phase-scrape-results.ts";

interface MatchJson {
    num?: number;
    team1: string;
    team2: string;
    score?: {
        ft?: [number, number];
        et?: [number, number];
        p?: [number, number];
    };
}

interface ParsedResult {
    id: number;
    result: "home" | "away" | null;
    homeScore: number | null;
    awayScore: number | null;
    homeShootout: number | null;
    awayShootout: number | null;
    home: string;
    away: string;
}

async function main() {
    console.log(`Fetching ${JSON_URL} ...\n`);

    const data = await fetch(JSON_URL).then(r => r.json()) as { matches?: MatchJson[] };
    const matches: MatchJson[] = data.matches ?? [];

    // Only knockout matches have a "num" field (73–104)
    const koMatches = matches.filter(m => typeof m.num === "number" && m.num >= 73 && m.num <= 104);
    console.log(`Found ${koMatches.length} knockout matches\n`);

    const results: ParsedResult[] = [];

    for (const m of koMatches) {
        const id = m.num!;
        const home = m.team1;
        const away = m.team2;

        if (!m.score) {
            console.log(`  [${id}] ${home} vs ${away} — no score yet`);
            results.push({ id, result: null, homeScore: null, awayScore: null, homeShootout: null, awayShootout: null, home, away });
            continue;
        }

        const { ft, et, p } = m.score;

        // Pick the right score: et overrides ft
        const mainScore = et ?? ft;
        if (!mainScore) {
            console.log(`  [${id}] ${home} vs ${away} — score object present but no ft/et`);
            results.push({ id, result: null, homeScore: null, awayScore: null, homeShootout: null, awayShootout: null, home, away });
            continue;
        }

        const [homeScore, awayScore] = mainScore;

        // Penalty shootout
        const homeShootout = p ? p[0] : null;
        const awayShootout = p ? p[1] : null;

        // Determine winner: penalties take priority, otherwise main score
        let result: "home" | "away" | null = null;
        if (p) {
            result = p[0] > p[1] ? "home" : "away";
        } else if (homeScore > awayScore) {
            result = "home";
        } else if (awayScore > homeScore) {
            result = "away";
        }

        const pens = p ? ` (${p[0]}-${p[1]} pens)` : "";
        const scoreType = et ? "aet" : "";
        console.log(`  [${id}] ${home} ${homeScore}-${awayScore} ${away}${scoreType ? ` (${scoreType})` : ""}${pens} → ${result}`);

        results.push({ id, result, homeScore, awayScore, homeShootout, awayShootout, home, away });
    }

    // Sort by fixture ID
    results.sort((a, b) => a.id - b.id);

    // Build output file
    const lines: string[] = [
        "// Auto-generated by scripts/scrape-knockout.ts — do not edit",
        "//",
        `// ${results.filter(r => r.result != null).length} knockout match results scraped from openfootball worldcup.json`,
        "//",
        "",
        "export interface KnockoutScrapeResult {",
        '  result: "home" | "away" | null;',
        "  homeScore: number | null;",
        "  awayScore: number | null;",
        "  homeShootout: number | null;",
        "  awayShootout: number | null;",
        "}",
        "",
        "/**",
        " * Knockout match results keyed by fixture ID (73–104).",
        " * A match is considered incomplete (null result) until scraped.",
        " */",
        "export const knockoutPhaseScrapeResults: Record<number, KnockoutScrapeResult> = {",
    ];

    for (const r of results) {
        if (r.result === null) {
            lines.push(`  // #${r.id} ${r.home} vs ${r.away} — not yet played`);
        } else {
            const shootout = r.homeShootout != null ? ` pens(${r.homeShootout}-${r.awayShootout})` : "";
            const etNote = (r.homeScore === r.awayScore && r.result) ? " aet" : "";
            lines.push(`  // ${r.home} ${r.homeScore}–${r.awayScore} ${r.away}${etNote}${shootout}`);
            const obj = JSON.stringify({
                result: r.result,
                homeScore: r.homeScore,
                awayScore: r.awayScore,
                homeShootout: r.homeShootout,
                awayShootout: r.awayShootout,
            });
            lines.push(`  "${r.id}": ${obj},`);
        }
    }

    lines.push("};");
    lines.push("");

    writeFileSync(OUT, lines.join("\n"));
    const withResults = results.filter(r => r.result != null).length;
    console.log(`\nDone: ${withResults} results → ${OUT}`);
}

main();
