/**
 * Scrape knockout match results from worldcupstats.football.
 *
 * Usage: npx tsx scripts/scrape-knockout.ts
 *
 * Currently a placeholder — knockout matches haven't started yet.
 * Once matches begin, this will fetch the knockout bracket page(s),
 * parse match results, and write them to src/data/knockout-phase-scrape-results.ts.
 */

// @ts-ignore
import { writeFileSync } from "fs";

const OUT = "src/data/knockout-phase-scrape-results.ts";

// ── Placeholder (no scraping yet) ──────────────────────────────────────────

function main() {
    const lines: string[] = [
        "// Auto-generated by scripts/scrape-knockout.ts — do not edit",
        "//",
        "// Knockout-phase match results scraped from worldcupstats.football",
        "// Currently empty — no knockout matches have been played yet.",
        "//",
        "",
        "export interface KnockoutScrapeResult {",
        '  result: "home" | "away" | null;',
        "  homeScore: number | null;",
        "  awayScore: number | null;",
        "  homeShootout: number | null;",
        "  awayShootout: number | null;",
        "}",
        "",
        "/**",
        " * Knockout match results keyed by fixture ID (73–104).",
        " * A match is considered incomplete (null result) until scraped.",
        " */",
        "export const knockoutPhaseScrapeResults: Record<number, KnockoutScrapeResult> = {};",
        "",
    ];

    writeFileSync(OUT, lines.join("\n"));
    console.log(`Knockout scrape results written to ${OUT} (0 results — placeholder)`);
}

main();
